#
#FILE
#	/unxsBase/unxsLib/unxsOath/Makefile
#AUTHOR/LEGAL
#	(C) 2006-2017 Gary Wallis for Unixservice, LLC.
#PURPOSE
#

install: liboath.a oath.h
	mkdir -p /usr/lib/oath
	cp -i ./liboath.a /usr/lib/oath/liboath.a
	mkdir -p /usr/include/liboath
	cp -i ./oath.h /usr/include/liboath/oath.h
